### ISSUE TITLE
[bug]修改表单选项，触发生成代码失败

### ISSUE THREAD

**Issue by AlexZhong22c** [Liugq5713/vue-element-form-editor#6]
vue-element-nocode-admin/src/views/FormEditor/FormCode/index.vue

`watch form`应该改为`watch formAttribute`

**Comment by Liugq5713** [comment]
多谢，已经修复了。（可能代码改来改去我给改漏了）

**Comment by Liugq5713** [comment]
> vue-element-nocode-admin/src/views/FormEditor/FormCode/index.vue
> 
> `watch form`应该改为`watch formAttribute`

已修复，多谢提bug
